name = "Samaritans_Official";					// name
picture = "images/sglogo512.paa";							// picture in expanded description
logoSmall = "images/sglogo150.paa";					// icon next to mod name when description is not expanded
logo = "images/sglogo150.paa";							// logo below game menu
logoOver = "images/sglogo150.paa";							// on mouse hover over logo
tooltip = "Click the mod to join the Discord";							// tool tip on mouse hover
overview = "Samaritan Gamings Server Files"; 						// overview
action = "https://discord.samaritangaming.com/";					// link
author = "Warden";								// author
version = "1.0";								// version